@startuml    水箱状态图
scale 500 width
[*] --> ok : 检测
[*] --> break : 检测

state ok{
    [*] --> 关
    state 关{
    [*] --> 有水 : 检测
    有水 --> 温度低于20度 : 检测
    温度低于20度 --> 开
    }
    state 开{
        [*] -> 温度达到120度 : 烧水
        关 <-  温度达到120度
        缺水 <- [*] : 检测水位
        关 <-  缺水
    }
}

state break{
    [*] --> 水箱损坏
    水箱损坏 --> 维修
}

