@startuml ControlPanel状态图
scale 500 width
[*] --> input  : 读取键盘状态
[*] --> lock : 读取键盘状态
input --> 输入
lock --> 等待
lock --> 键盘状态错误
等待 --> 输入 : 等待时间到
输入 --> 密码错误 : 对比
state 密码错误{
    [*] --> 错误次数少于3
    错误次数少于3 --> 输入
    [*] --> 错误次数大于3
    错误次数大于3 --> 等待
}
输入 --> 密码正确 : 对比
密码正确 --> 系统功能状态